# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f89c16c6f920bf0692eea2a9f16656b6090b7d4536a95727fa7c3765d45b07697e42e32ecd97e71c3ed1524c393d02d4a072b581f6876aa0db079e8691d3a6c8

test:
  secret_key_base: a665fcf30f61e288cdcacdedce2e19ea99adf3c33be9cff6b6fe6646a1b72cbb341370c49e349d0166ef993abf9940d1824436b5a3c2d401763022d9ddfa1911

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
